import { assetPath } from './assetPath';

const ICON_PATH_BY_FILENAME: Record<string, string> = {
  'emoji_coin.png': '/assets/icons/generic_buttons/emoji_coin.png',
  'emoji_seed.png': '/assets/icons/generic_buttons/emoji_seed.png',
  'emoji_sunflower.png': '/assets/icons/generic_buttons/emoji_sunflower.png',
  'icon_barn.png': '/assets/icons/generic_buttons/icon_barn.png',
  'icon_boost.png': '/assets/icons/store/icon_boost.png',
  'icon_coin.png': '/assets/icons/coins/icon_coin_garden_1.png',
  'icon_coin_boost.png': '/assets/icons/coins/icon_coin_boost.png',
  'icon_coin_flower.png': '/assets/icons/coins/icon_coin_garden_1.png',
  'icon_coin_fruit.png': '/assets/icons/coins/icon_coin_garden_2.png',
  'icon_coin_general.png': '/assets/icons/coins/icon_coin_general.png',
  'icon_coin_small.png': '/assets/icons/coins/icon_coin_small_garden_1.png',
  'icon_coin_vegetable.png': '/assets/icons/coins/icon_coin_garden_3.png',
  'icon_coin_watchad.png': '/assets/icons/coins/icon_coin_watchad.png',
  'icon_coinmultiplier_1.png': '/assets/icons/store/icon_coinmultiplier_1.png',
  'icon_coinmultiplier_2.png': '/assets/icons/store/icon_coinmultiplier_2.png',
  'icon_coinmultiplier_3.png': '/assets/icons/store/icon_coinmultiplier_3.png',
  'icon_cropmerge.png': '/assets/icons/upgrades/icon_cropmerge.png',
  'icon_cropsynergy.png': '/assets/icons/upgrades/icon_cropsynergy.png',
  'icon_cropvalue.png': '/assets/icons/upgrades/icon_cropvalue.png',
  'icon_customerspeed.png': '/assets/icons/upgrades/icon_customerspeed.png',
  'icon_extracustomer.png': '/assets/icons/upgrades/icon_extracustomer.png',
  'icon_farm.png': '/assets/icons/generic_buttons/icon_farm.png',
  'icon_farmerpack.png': '/assets/icons/store/icon_farmerpack.png',
  'icon_fb_gardens.png': '/assets/icons/floating_buttons/icon_fb_gardens.png',
  'icon_fb_gardens_locked.png': '/assets/icons/floating_buttons/icon_fb_gardens_locked.png',
  'icon_fb_noads.png': '/assets/icons/floating_buttons/icon_fb_noads.png',
  'icon_fb_starterpack.png': '/assets/icons/floating_buttons/icon_fb_starterpack.png',
  'icon_fb_tasks_claim.png': '/assets/icons/floating_buttons/icon_fb_tasks_claim.png',
  'icon_fb_tasks_completed.png': '/assets/icons/floating_buttons/icon_fb_tasks_completed.png',
  'icon_fb_tasks_locked.png': '/assets/icons/floating_buttons/icon_fb_tasks_locked.png',
  'icon_fb_tasks_normal.png': '/assets/icons/floating_buttons/icon_fb_tasks_normal.png',
  'icon_fetilesoil.png': '/assets/icons/upgrades/icon_fetilesoil.png',
  'icon_finger.png': '/assets/ui/generic/ui_finger.png',
  'icon_goal_1.png': '/assets/icons/goals/garden_1/icon_goal_1.png',
  'icon_goal_10.png': '/assets/icons/goals/garden_1/icon_goal_10.png',
  'icon_goal_11.png': '/assets/icons/goals/garden_1/icon_goal_11.png',
  'icon_goal_12.png': '/assets/icons/goals/garden_1/icon_goal_12.png',
  'icon_goal_13.png': '/assets/icons/goals/garden_1/icon_goal_13.png',
  'icon_goal_14.png': '/assets/icons/goals/garden_1/icon_goal_14.png',
  'icon_goal_15.png': '/assets/icons/goals/garden_1/icon_goal_15.png',
  'icon_goal_16.png': '/assets/icons/goals/garden_1/icon_goal_16.png',
  'icon_goal_17.png': '/assets/icons/goals/garden_1/icon_goal_17.png',
  'icon_goal_18.png': '/assets/icons/goals/garden_1/icon_goal_18.png',
  'icon_goal_19.png': '/assets/icons/goals/garden_1/icon_goal_19.png',
  'icon_goal_2.png': '/assets/icons/goals/garden_1/icon_goal_2.png',
  'icon_goal_20.png': '/assets/icons/goals/garden_1/icon_goal_20.png',
  'icon_goal_21.png': '/assets/icons/goals/garden_1/icon_goal_21.png',
  'icon_goal_22.png': '/assets/icons/goals/garden_1/icon_goal_22.png',
  'icon_goal_23.png': '/assets/icons/goals/garden_1/icon_goal_23.png',
  'icon_goal_24.png': '/assets/icons/goals/garden_1/icon_goal_24.png',
  'icon_goal_3.png': '/assets/icons/goals/garden_1/icon_goal_3.png',
  'icon_goal_4.png': '/assets/icons/goals/garden_1/icon_goal_4.png',
  'icon_goal_5.png': '/assets/icons/goals/garden_1/icon_goal_5.png',
  'icon_goal_6.png': '/assets/icons/goals/garden_1/icon_goal_6.png',
  'icon_goal_7.png': '/assets/icons/goals/garden_1/icon_goal_7.png',
  'icon_goal_8.png': '/assets/icons/goals/garden_1/icon_goal_8.png',
  'icon_goal_9.png': '/assets/icons/goals/garden_1/icon_goal_9.png',
  'icon_goldenpot.png': '/assets/icons/collection/icon_goldenpot.png',
  'icon_happycustomer.png': '/assets/icons/upgrades/icon_happycustomer.png',
  'icon_harvest.png': '/assets/icons/upgrades/icon_harvest.png',
  'icon_harvestboost.png': '/assets/icons/upgrades/icon_harvestboost.png',
  'icon_harvestspeed.png': '/assets/icons/upgrades/icon_harvestspeed.png',
  'icon_level.png': '/assets/ui/generic/ui_level_garden_1.png',
  'icon_lock.png': '/assets/icons/generic_buttons/icon_lock.png',
  'icon_lock_collection.png': '/assets/icons/collection/icon_lock_collection.png',
  'icon_logo.png': '/assets/ui/generic/ui_logo.png',
  'icon_luckyharvest.png': '/assets/icons/upgrades/icon_luckyharvest.png',
  'icon_luckymerge.png': '/assets/icons/upgrades/icon_luckymerge.png',
  'icon_luckyseed.png': '/assets/icons/upgrades/icon_luckyseed.png',
  'icon_market.png': '/assets/icons/generic_buttons/icon_market.png',
  'icon_marketvalue.png': '/assets/icons/upgrades/icon_marketvalue.png',
  'icon_mergeharvest.png': '/assets/icons/upgrades/icon_mergeharvest.png',
  'icon_noads.png': '/assets/icons/store/icon_noads.png',
  'icon_plantmastery.png': '/assets/icons/collection/icon_plantmastery.png',
  'icon_plotexpansion.png': '/assets/icons/upgrades/icon_plotexpansion.png',
  'icon_premiumorders.png': '/assets/icons/upgrades/icon_premiumorders.png',
  'icon_seedproduction.png': '/assets/icons/upgrades/icon_seedproduction.png',
  'icon_seedquality.png': '/assets/icons/upgrades/icon_seedquality.png',
  'icon_seedstorage.png': '/assets/icons/upgrades/icon_seedstorage.png',
  'icon_seedstorm.png': '/assets/icons/upgrades/icon_seedstorm.png',
  'icon_seedsurplus.png': '/assets/icons/upgrades/icon_seedsurplus.png',
  'icon_star_brown.png': '/assets/icons/rateus/icon_star_brown.png',
  'icon_star_gold.png': '/assets/icons/rateus/icon_star_gold.png',
  'icon_star_gold_completed.png': '/assets/icons/rateus/icon_star_gold_completed.png',
  'icon_starterpack.png': '/assets/icons/store/icon_starterpack.png',
  'icon_surplussales.png': '/assets/icons/upgrades/icon_surplussales.png',
  'icon_watchad.png': '/assets/icons/generic_buttons/icon_watchad.png',
  'icon_watchad_large.png': '/assets/icons/generic_buttons/icon_watchad_large.png',
};

/** Resolve a bare icon filename (e.g. from level-unlock rows) to a full asset path. */
export function iconAssetPath(filename: string): string {
  const key = filename.includes('/') ? filename.split('/').pop()! : filename;
  const mapped = ICON_PATH_BY_FILENAME[key];
  if (mapped) return assetPath(mapped);
  return assetPath(filename.startsWith('/') ? filename : `/assets/icons/upgrades/${key}`);
}
